---
title: "week5-ex"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(sf)
library(terra)
library(dplyr)
library(lubridate)
library(ggplot2)
library(tmap)
library(sp)
library(devtools)
library(ComputationalMovementAnalysisData)
#install.packages("devtools")

devtools::install_github("ComputationalMovementAnalysis/ComputationalMovementAnalysisData")

```


# show data
```{r cars}
head(wildschwein_BE)
head(wildschwein_metadata)
head(wildschwein_overlap_temp)
head(schreck_agenda)
head(schreck_locations)
```

# Schreck prepare
```{r }
schreck_locations_ch <- schreck_locations %>% st_as_sf(coords = c("lon", "lat"), crs = CRS("+init=epsg:4326"), remove = FALSE)  #%>% st_transform(crs = 2056)
schreck_locations_ch <- schreck_locations_ch %>% st_transform(crs = 2056)
schreck_locations_ch <- schreck_locations_ch %>% filter(lat < 47.2 & lon < 7.5)
coordsne <- unlist(st_geometry(schreck_locations_ch)) %>% matrix(ncol=2,byrow=TRUE) %>% as_tibble() %>% setNames(c("N","E"))
schreck_locations_ch$N <- coordsne$E
schreck_locations_ch$E <- coordsne$N
#join 
schreck_locations_ch <- schreck_locations_ch %>% left_join(schreck_agenda, by=c("id"="id"))
schreck_locations_ch$wid <- c(1:25)
schreck_locations_ch <- schreck_locations_ch %>% mutate(wid=as.character(wid))
```

# Get common data, show examples
```{r }
# Get common samples
head(wildschwein_BE)
head(schreck_locations_ch)
sabi <- wildschwein_BE %>% filter(TierName=="Sabine")
# Filter night data
sabi <- sabi %>% filter(day != "Tag" & !is.na(day)) # only night gps

s1 <- schreck_locations_ch[5,]
sabi <- sabi %>% filter(DatetimeUTC > first(s1$datum_on) & DatetimeUTC < first(s1$datum_off))
sabi <- sabi %>% mutate(dist = sqrt((first(s1$N)-N)^2+(first(s1$E)-E)^2))
sabi <- sabi %>% filter(dist < 400)
sabi <- sabi %>% mutate(trip = ifelse(hour(DatetimeUTC) > 16, day(DatetimeUTC)+1, day(DatetimeUTC)))


ggplot() +
  geom_path(data=sabi %>%  filter(trip<11), aes(x=E, y=N, color=factor(trip))) +
  geom_point(data = s1, aes(x=E, y=N), colour="black", size=2) 

# Get example 1
wildboar_closeup <- wildschwein_BE %>% 
  filter(TierName=="Sabine" & DatetimeUTC > as_datetime('2015-06-09 22:30:43') & DatetimeUTC < as_datetime('2015-06-10 14:30:43')) %>% 
  mutate(dist = sqrt((first(s1$N)-N)^2+(first(s1$E)-E)^2)) %>% mutate(time0 = as.numeric((DatetimeUTC - min(DatetimeUTC))) / 60)
ggplot() +
  geom_path(data=wildboar_closeup, aes(x=E, y=N, color=time0)) +
  geom_point(data = s1, aes(x=E, y=N), colour="black", size=2) 
# Get example 2
wildboar_closeup1 <- wildschwein_BE %>% 
  filter(TierName=="Sabine" & DatetimeUTC > as_datetime('2015-06-08 18:30:43') & DatetimeUTC < as_datetime('2015-06-09 14:30:43')) %>% 
  mutate(dist = sqrt((first(s1$N)-N)^2+(first(s1$E)-E)^2)) %>% mutate(time0 = as.numeric((DatetimeUTC - min(DatetimeUTC))) / 60) %>% arrange(.,time0)
ggplot() +
  geom_path(data=wildboar_closeup1, aes(x=E, y=N, color=time0)) +
  geom_point(data = s1, aes(x=E, y=N), colour="black", size=2) 
# Get example 2
wildboar_closeup2 <- wildschwein_BE %>% 
  filter(TierName=="Sabine" & DatetimeUTC > as_datetime('2015-06-07 18:30:43') & DatetimeUTC < as_datetime('2015-06-08 14:30:43')) %>% 
  mutate(dist = sqrt((first(s1$N)-N)^2+(first(s1$E)-E)^2)) %>% mutate(time0 = as.numeric((DatetimeUTC - min(DatetimeUTC))) / 60) %>% arrange(.,time0)
ggplot() +
  geom_path(data=wildboar_closeup2, aes(x=E, y=N, color=time0)) +
  geom_point(data = s1, aes(x=E, y=N), colour="black", size=2) 

# Plot
head(schreck_locations_ch)
ggplot() +
  geom_sf(data = schreck_locations_ch, color='black') +
  geom_sf(data=wildschwein_BE %>% filter(TierName=="Sabi"), color="blue")

ggplot() +
  geom_point(data = schreck_locations_ch, aes(x=E, y=N, color='red')) +
  geom_point(data=sabi, aes(x=E, y=N,color="blue")) + ylim(1200000, 1210000) +  xlim(2568000, 2578000)
sabi %>% filter(day==10)



```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

# Adding closest active schreck (+ distance) to each observation
```{r }
### data
w<-wildschwein_BE  
sl<-schreck_locations

###
s<-data.frame(schreck_locations_ch) ## I had to transform it to a data frame, otherwise something was weird about the coordinates (geometry)
###

s1<-s[!duplicated(s$id),c("id","N","E")] # list with all Schrecks and their location

# Set id to w
w <- w %>% mutate(id = row_number())

## reduce data to certain time frame
w1<-w %>% 
  filter (day!="Tag"&!is.na(day) &
            ((DatetimeUTC > as.Date("2014-05-01") & DatetimeUTC < as.Date("2014-07-04")) | 
                (DatetimeUTC > as.Date("2015-05-20") & DatetimeUTC < as.Date("2015-07-01")) |
                 (DatetimeUTC > as.Date("2016-04-04") & DatetimeUTC < as.Date("2016-10-04")) |
                 (DatetimeUTC > as.Date("2017-04-26") & DatetimeUTC < as.Date("2017-11-18"))))
nrow(w1)


#for(j in 1:nrow(w1)){
### look only at Schrecks that were active on that day
 # s_on<-s[s$datum_on < w1[j,]$DatetimeUTC & s$datum_off > w1[j,]$DatetimeUTC,]
  #if(nrow(s_on)==0)
   # {w1[j,"closest_schreck"]<-"no_Schreck_on"}  
  #else{     
    #for(i in 1:nrow(s_on)){ ## calculate difference between current observation (j) and each schreck location
      #s_on[i,"diff"]<-sqrt((w1[j,"N"]-s_on[i,"N"])^2+(w1[j,"E"]-s_on[i,"E"])^2)} ## add difference of current observation to location into file
#### look at the distance of the closest Schreck, only use it if less than 400m
  #if(min(s_on$diff)>400){
      #w1[j,"closest_schreck"]<-"no_Schreck_witin_400m"} 
  #else{
      #w1[j,"closest_schreck"]<-s_on[s_on$diff==min(s_on$diff),"id"]  ## add closest schreck to each wild boar location
      #w1[j,"distance_to_closest_schreck"]<-s_on[s_on$diff==min(s_on$diff),"diff"]
#}}}

# Save data.frame to spare time
#write.csv(w1, "wildboar_loop.csv")

w1 <- read_delim("wildboar_loop.csv",",")

# Merge close wildschweinschreck gps  data to origin wildboar
w <- w %>% left_join(w1 %>% dplyr::select(id, closest_schreck, distance_to_closest_schreck), by="id")
w <- w %>% mutate(closest_schreck= 
  ifelse(is.na(closest_schreck), "no_Schreck_witin_400m", closest_schreck))

```

# Separation of the wildboar trips
```{r }

####### create trips: two hour before and two hours after first observation at "Abenddaemmerung" (i.e. presumed start of Schrecks)
#####

# split time and day in separate columns:
w1$Date <- as.Date(w1$DatetimeUTC)
## order data frame by animal and time
w1<-w1[order(w1$TierName) & order(w1$DatetimeUTC),]
## empty column for trip id
w$tripID<-"NA"
w$start<-"no"
animals<-unique(w$TierName)

for(j in 1:length(animals)){
  days<-unique(w1[w1$TierName==animals[j],]$Date) 
  if(length(days)!=0){
  for(i in 1:length(days)){
    n<-w1[w1$TierName==animals[j] & w1$Date==days[i]& w1$day=="Abenddaemmerung",]
    n<-n[1,]
    if(nrow(n)!=0 & !is.na(n$TierID)){
    w[w$TierName==animals[j] & (w$DatetimeUTC >= n$DatetimeUTC-2*60*60) & (w$DatetimeUTC <= n$DatetimeUTC+2*60*60),"tripID"]<-paste(animals[j],i, sep="_")
    w[w$TierName==animals[j] & w$DatetimeUTC==n$DatetimeUTC,"start"]<-"yes"
    }}}}

## correct NA again
w[w$tripID=="NA","tripID"]<-NA
table(w$tripID)

data.frame(w[w$tripID=="Ueli_85",])

### new data frame with only those trips that are at least one point within 400m of schreck (active)
w_start <-w[!is.na(w$tripID) & w$closest_schreck!="no_Schreck_on" & w$closest_schreck!="no_Schreck_witin_400m",]

trips<-unique(ww$tripID)
#

##### Create trips: with shorest distance to schreck (each day) ########################################

# split time and day in separate columns:
w1$Date <- as.Date(w1$DatetimeUTC)

## order data frame by animal and time
w1<-w1[order(w1$TierName) & order(w1$DatetimeUTC),]
## empty column for trip id
w$tripID_dist<-"NA"
w$start_dist<-"no"
animals<-unique(w1$TierName)
for(j in 1:length(animals)){
  days<-unique(w1[w1$TierName==animals[j] & !is.na(w1$TierName),]$Date) 
  if(length(days)!=0){
    for(i in 1:length(days)){
      n<-w1[w1$TierName==animals[j] & w1$Date==days[i],]
      if(nrow(n[!is.na(n$distance_to_closest_schreck),])==0){nmin<-NA} else{
      nmin<-min(n$distance_to_closest_schreck,na.rm=T)}
      if(!is.na(nmin)){ ## only continue if nmin is not NA
        if(nmin<=400){ ## only continue if minimal distance to schreck is less than 400m
      n<-n[n$distance_to_closest_schreck==nmin & !is.na(n$distance_to_closest_schreck),]
        w[w$TierName==animals[j] & (w$DatetimeUTC >= n$DatetimeUTC-2*60*60) & (w$DatetimeUTC <= n$DatetimeUTC+2*60*60),"tripID_dist"]<-paste(animals[j],i, sep="_")
        w[w$TierName==animals[j] & w$DatetimeUTC==n$DatetimeUTC,"start_dist"]<-"yes"
      }}}}}

### list of all trips based on closest distance per day and two hours before and after
trips_dist<-unique(w$tripID_dist)

head(trips_dist)

```

# Wildschewinschreck
```{r}
# calculate properties of scarce (approaching rate, speed)
wildboar_closeup <- wildschwein_BE %>% 
  filter(TierName=="Sabine" & DatetimeUTC > as_datetime('2015-06-08 18:30:43') & DatetimeUTC < as_datetime('2015-06-09 10:30:43')) %>% 
  mutate(dist = sqrt((first(s1$N)-N)^2+(first(s1$E)-E)^2)) %>% mutate(time0 = as.numeric((DatetimeUTC - min(DatetimeUTC))) / 60) %>% arrange(.,time0)

schreck_orientation <- s1 %>% mutate(length=lautstaerke*lautstaerke/100)
rad2deg <- function(rad) {(rad * 180) / (pi)}
deg2rad <- function(deg) {(deg * pi) / (180)}

schreck_orientation$asurichtung_mean <- (schreck_orientation$ausrichtung_max-
                                           schreck_orientation$ausrichtung_min) / 2 +
                                        schreck_orientation$ausrichtung_min
schreck_orientation$ausrichung_meanE = schreck_orientation$E[1] + schreck_orientation$length[1] * 2*
  cos(deg2rad(360-270-(schreck_orientation$asurichtung_mean[1])))
schreck_orientation$ausrichung_meanN = schreck_orientation$N[1] + schreck_orientation$length[1] *2* 
  sin(deg2rad(360-270-(schreck_orientation$asurichtung_mean[1])))

schreck_orientation$ausrichung_minE = schreck_orientation$E[1] + schreck_orientation$length[1] * 
  cos(deg2rad(360-270-schreck_orientation$ausrichtung_min[1]))
schreck_orientation$ausrichung_minN = schreck_orientation$N[1] + schreck_orientation$length[1] * 
  sin(deg2rad(360-270-schreck_orientation$ausrichtung_min[1]))
schreck_orientation$ausrichung_maxE = schreck_orientation$E[1] + schreck_orientation$length[1] * 
  cos(deg2rad(360-270-schreck_orientation$ausrichtung_max[1]))
schreck_orientation$ausrichung_maxN = schreck_orientation$N[1] + schreck_orientation$length[1] * 
  sin(deg2rad(360-270-schreck_orientation$ausrichtung_max[1]))


x_coord <- c(schreck_orientation$E[1],  schreck_orientation$ausrichung_minE[1],
             schreck_orientation$ausrichung_meanE[1],
             schreck_orientation$ausrichung_maxE[1], schreck_orientation$E[1])
y_coord <- c(schreck_orientation$N[1], schreck_orientation$ausrichung_minN[1],
             schreck_orientation$ausrichung_meanN[1],
             schreck_orientation$ausrichung_maxN[1], schreck_orientation$N[1])
#p = Polygon(cbind(x_coord, y_coord))
#ps = Polygons(list(p),1)
#sps = SpatialPolygons(list(ps))
#plot(sps)
#schreck_orientation$polygon[1] = sps[1]
poly <- st_polygon(list(matrix(c(x_coord, y_coord),ncol=2, byrow=FALSE))) #%>% st_geometry(poly) %>% st_set_crs(2056)
pos <- data.frame(x=x_coord, y=y_coord, id=c(1,2,3,4,5))
#schreck_orientation$polygon <- poly 
                                                                        

ggplot() +
  geom_path(data=wildboar_closeup, aes(x=E, y=N, color=time0)) +
  geom_point(data = s1, aes(x=E, y=N), colour="black", size=2) +
  geom_point(data = schreck_orientation, aes(x=ausrichung_meanE, y=ausrichung_meanN), 
             colour="brown", size=2) +
  geom_polygon(data=pos, aes(x=x, y = y, fill="orange", alpha=0.4))


```